language: julia
os:
    - linux
julia:
    - 1.0
    - nightly
matrix:
  allow_failures:
    - julia: nightly
      
notifications:
    email: false

services:
  - docker

before_script:
  - docker-compose up -d
  - echo exit | telnet localhost 19092
    
after_success:
    # push coverage results to Codecov
    - julia -e 'cd(Pkg.dir("RDKafka")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'